version: '3.8'

services:
  fastapi:
    container_name: fastapi
    build: .
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - fastapiNet

  postgresdb:
    container_name: postgresdb
    image: postgres:14-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    networks:
      - fastapiNet


networks:
  fastapiNet:
    driver:
      bridge